<div class="page-header">
    <h1>
        Card management
    </h1>
    <!--	Create if statement that only shows when logged in and admin+-->
    <p>
        <?php echo $this->tag->linkTo(["cards", "Back to overview of all the public cards"]) ?>
    </p>
</div>

<?php echo $this->getContent(); ?>


<?php echo $this->tag->form("cards/manage"); ?>
Filter:
<?php echo $this->tag->selectStatic(
    [
        "filter",
        [
            "All" => "All",
            "1" => "Public",
            "0" => "Private",
        ]
    ]
);
echo $this->tag->submitButton([">>"]);
echo $this->tag->endForm();
?>


<div class="row">
    <table class="table table-bordered">
        <thead>
        <tr>
            <th>Id</th>
            <th>Title</th>
            <th>Text</th>
            <th>Sender</th>
            <th>Reciever</th>
            <th>Likes</th>
<!--            <th>Public / Private</th>-->
            <th>Knopje</th>
        </tr>
        </thead>
        <tbody>
        <?php foreach ($page->items as $cards): ?>
            <tr>
                <td><?php echo $cards->id ?></td>
                <td><?php echo $cards->title ?></td>
                <td><?php echo $cards->text ?></td>
                <td><?php echo $cards->user->id ?> | <?= $cards->user->username ?></td>
                <td><?php echo $cards->reciever ?></td>
                <td><?php echo $cards->likes ?></td>
<!--                <td>-->
<!--                    --><?php //if($cards->public == 1){
//                        echo("public");
//                    }
//                    else{
//                        echo("private");
//                    }
//                    ?>
<!--                </td>-->

                <td>


                    <?php
                    echo $this->tag->form("cards/publicate");
                    echo $this->tag->hiddenField(["id", "value" => $cards->id]);
                    if($cards->public == 0){
                        echo $this->tag->submitButton(["private", "class" => "btn btn-info"]);

                    }
                    else{
                        echo $this->tag->submitButton(["public", "class" => "btn btn-success"]);
                    }
                    echo $this->tag->endForm();
                    ?>
                    <?php echo $this->tag->linkTo(["cards/delete/" . $cards->id, "Delete", "class" => "btn btn-danger"]); ?>
                </td>
            </tr>
        <?php endforeach; ?>
        </tbody>
    </table>
</div>


<div class="row">
    <div class="col-sm-1">
        <p class="pagination" style="line-height: 1.42857;padding: 6px 12px;">
            <?php echo $page->current, "/", $page->total_pages ?>
        </p>
    </div>
    <div class="col-sm-11">
        <nav>
            <ul class="pagination">
                <li><?php echo $this->tag->linkTo("news", "First") ?></li>
                <li><?php echo $this->tag->linkTo("news?page=" . $page->before, "Previous") ?></li>
                <li><?php echo $this->tag->linkTo("news?page=" . $page->next, "Next") ?></li>
                <li><?php echo $this->tag->linkTo("news?page=" . $page->last, "Last") ?></li>
            </ul>
        </nav>
    </div>
</div>
