<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>

<div class="row">
    <nav>
        <ul class="pager">
            <li class="previous"><?php echo $this->tag->linkTo(["cards", "Go Back"]) ?></li>
        </ul>
    </nav>
</div>

<div class="page-header">
    <h1>
        Create card
    </h1>
</div>

<?php echo $this->getContent(); ?>

<?php
echo $this->tag->form(
    [
        "cards/create",
        "autocomplete" => "off",
        "class" => "form-horizontal"
    ]
);
?>

<div class="form-group">
    <label for="fieldTitle" class="col-sm-2 control-label">Title</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["title", "size" => 30, "class" => "form-control", "id" => "fieldTitle"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldText" class="col-sm-2 control-label">Text</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["text", "size" => 30, "class" => "form-control", "id" => "fieldText"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldSender" class="col-sm-2 control-label">Sender</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["sender", "size" => 30, "class" => "form-control", "id" => "fieldSender"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldReciever" class="col-sm-2 control-label">Reciever</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["reciever", "type" => "number", "class" => "form-control", "id" => "fieldReciever"]) ?>
    </div>
</div>



<div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
        <?php echo $this->tag->submitButton(["Save", "class" => "btn btn-default"]) ?>
    </div>
</div>

<?php echo $this->tag->endForm(); ?>
